### ISSUE TITLE
命名提议

### ISSUE THREAD

**Issue by nobodxbodon** [duolabmeng6/pyefun#1]
看到不少”是否“前缀的，比如：”文本_是否为汉字“，而”为“已有了判断之意，用“文本_全为汉字”亦可。
像“文本_是否为小写字母”去掉“是否”也可以。

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/119217378-70b76180-bb0c-11eb-959d-f86ab12af818.png)
为减少学习成本命名与精易模块命名保持了一致 你的建议收到这边会增加更加简洁的别名方便输入

**Comment by nobodxbodon** [comment]
另外，python 源码标识符和文件名可考虑用中文命名，如 codeConv、dirkBase、progiterUtil 等如改用中文后含义也许会更一目了然。

**Comment by duolabmeng6** [comment]
> 另外，python 源码标识符和文件名可考虑用中文命名，如 codeConv、dirkBase、progiterUtil 等如改用中文后含义也许会更一目了然。

文件名没办法使用中文会导致诡异的情况...ide无法运行测试用例..

**Comment by nobodxbodon** [comment]
问题信息可否帖一下？[木兰重现项目](https://gitee.com/MulanRevive/mulan-rework)  一直用的中文文件名，unittest 在 mac/linux/win 命令行下都跑过没问题。刚试了 pycharm 看起来也可以：
![Screen Shot 2021-05-22 at 12 21 37 AM](https://user-images.githubusercontent.com/392497/119218211-1c709b00-ba94-11eb-99a6-bc613a08d9cd.png)

**Comment by duolabmeng6** [comment]
> 问题信息可否帖一下？[木兰重现项目](https://gitee.com/MulanRevive/mulan-rework) 一直用的中文文件名，unittest 在 mac/linux/win 命令行下都跑过没问题。刚试了 pycharm 看起来也可以：
> ![Screen Shot 2021-05-22 at 12 21 37 AM](https://user-images.githubusercontent.com/392497/119218211-1c709b00-ba94-11eb-99a6-bc613a08d9cd.png)

![image](https://user-images.githubusercontent.com/59047063/119218397-abbc9380-bb12-11eb-92bb-995fc83aa8fe.png)
![image](https://user-images.githubusercontent.com/59047063/119218412-c2fb8100-bb12-11eb-8f2a-64cec1f4613e.png)

也不是跑不了就是特别麻烦.......每次都会弹出这个玩意

**Comment by duolabmeng6** [comment]
ide 报错 Error: Provide a qualified name of a function, class or module" 反正 也能运行 但是要按2遍 你是怎么解决的?

**Comment by nobodxbodon** [comment]
有时差，我这早上七点半刚起。方便的话能不能在 github 上传一个能复现这个问题的小示例项目？

**Comment by duolabmeng6** [comment]
> 有时差，我这早上七点半刚起。方便的话能不能在 github 上传一个能复现这个问题的小示例项目？

![image](https://user-images.githubusercontent.com/59047063/119240000-9b8ecd80-bb7f-11eb-982f-78f468f49b00.png)
```
import unittest

from .文本处理 import *


class Test文本处理(unittest.TestCase):

    def test_测试一下ide无法直接调试的问题(self):
        pass
        data = 测试一下ide无法直接调试的问题()


```

```
def 测试一下ide无法直接调试的问题():
    print("测试一下ide无法直接调试的问题")

```

![image](https://user-images.githubusercontent.com/59047063/119240014-b6f9d880-bb7f-11eb-844c-00d3ed91d0ec.png)
![image](https://user-images.githubusercontent.com/59047063/119240024-c37e3100-bb7f-11eb-9a31-704e421ae28c.png)

Error: Provide a qualified name of a function, class or module"

![image](https://user-images.githubusercontent.com/59047063/119240040-d55fd400-bb7f-11eb-8ca9-70b7a4cbc27a.png)

```
Launching unittests with arguments python -m unittest pyefun.文本处理_test.Test文本处理.test_测试一下ide无法直接调试的问题 in C:\python\pyefun\pyefun



Ran 1 test in 0.002s

OK
测试一下ide无法直接调试的问题

Process finished with exit code 0

```


虽然最终是可以运行 但是 实在是太麻烦了..这个问题我之前尝试解决了  尝试了 1小时左右 没办法解决 所以就是用了 英文命令文件名了

**Comment by duolabmeng6** [comment]
由于代码都需要测试用例来运行 所以 这个功能如果不能解决的话 不考虑把文件名都改成中文...
虽然改成中文命令很舒服 但是没办法调试了

**Comment by nobodxbodon** [comment]
在 [这个分支](https://github.com/nobodxbodon/pyefun/tree/%E4%B8%AD%E6%96%87%E5%91%BD%E5%90%8D) 加了上面测试代码。

IDE 版本：
PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
macOS 10.13.6

好像用的快捷方式有点不同：
![Screen Shot 2021-05-22 at 2 15 10 PM](https://user-images.githubusercontent.com/392497/119240959-3946b600-bb08-11eb-9667-859e7b00a007.png)
运行直接就通过了：
![Screen Shot 2021-05-22 at 2 16 38 PM](https://user-images.githubusercontent.com/392497/119241005-70b56280-bb08-11eb-9d61-15d953093080.png)
运行配置也不同（没改过）：
![Screen Shot 2021-05-22 at 2 17 56 PM-cover](https://user-images.githubusercontent.com/392497/119241107-f507e580-bb08-11eb-86de-c712b6afc9d7.png)

**Comment by duolabmeng6** [comment]
mac 我没测试 在window下开发的 因为要对照 精易模块和易语言核心支持库...

**Comment by nobodxbodon** [comment]
> 你点一下 测试方法里面的 运行图标 也可以吗 我window下对整个测试文件的运行也是没问题的..

哦，测试方法里面的 运行图标试出同样问题了。我看看没招的话向 JB 社区反映一下吧。

**Comment by duolabmeng6** [comment]
> > 你点一下 测试方法里面的 运行图标 也可以吗 我window下对整个测试文件的运行也是没问题的..
> 
> 哦，测试方法里面的 运行图标试出同样问题了。我看看没招的话向 JB 社区反映一下吧。

所以还是没办法 支持的话 我很乐意用中文文件名的
你可以帮忙跟jb提一下 他解决了我就改中文名字~~

**Comment by nobodxbodon** [comment]
看到这个 SO 帖子：[Pucharm unittest error: Provide a qualified name of function, class or a module](https://stackoverflow.com/questions/53120356/pucharm-unittest-error-provide-a-qualified-name-of-function-class-or-a-module)，看起来是 target 名字的正则检查限制。

在官方 tracker 找到了个韩国开发者提交的同样 issue：https://youtrack.jetbrains.com/issue/PY-35860 回头看看如何补充或另开。

**Comment by duolabmeng6** [comment]
他2年前提出的到现在都没解决~~我们去重新提一下吧

**Comment by nobodxbodon** [comment]
刚跟了个帖: https://youtrack.jetbrains.com/issue/PY-35860#focus=Comments-27-4908994.0-0 
看看下星期啥时候回应吧。

**Comment by duolabmeng6** [comment]
> 刚跟了个帖: https://youtrack.jetbrains.com/issue/PY-35860#focus=Comments-27-4908994.0-0
> 看看下星期啥时候回应吧。

重新开个帖子吧 用中文做示例叫他们修复

**Comment by nobodxbodon** [comment]
嗯，因为是相同问题就跟帖了，先看几天吧。没反应的话再开新帖。

**Comment by duolabmeng6** [comment]
> 嗯，因为是相同的问题就跟帖了，先看几天吧。没反应的话再开新帖。

他们有回复吗 能不能解决这个问题~

**Comment by nobodxbodon** [comment]
没看到回复，建了个新 issue：https://youtrack.jetbrains.com/issue/PY-49059

**Comment by nobodxbodon** [comment]
已有相同 issue 被合并了：https://youtrack.jetbrains.com/issue/PY-48747

**Comment by duolabmeng6** [comment]
大佬这个bug他们修复了没

**Comment by nobodxbodon** [comment]
> 大佬这个bug他们修复了没

没看出是否已开始着手。从这个 [SO 帖子看来](https://stackoverflow.com/questions/53120356/pucharm-unittest-error-provide-a-qualified-name-of-function-class-or-a-module)，只要把 [isWellFormed](https://github.com/JetBrains/intellij-community/blob/76054d809dc7649d0df64ad1ecc45514feb0bc34/python/src/com/jetbrains/python/testing/PyTestsShared.kt#L285) 的条件放宽就可以，我在一开始建的 PY-49059 里也提到了，不知道他们是不是有其他的考虑。

自己构建一个pycharm不知是否可行，有空的话可以试试。

说个题外话，有没有认识自己搞开源IDE项目的？虽然现在有中文补全辅助插件，但毕竟受限于现有IDE的API和补全机制，长远来看必然有需求开发适合中文开发者的IDE（短期内也许需要倚靠定制现有IDE实现）。早先有过一些 [相关讨论](https://github.com/program-in-chinese/overview/issues/11)。最近看到 [hbuilderx](https://www.dcloud.io/hbuilderx.html)，虽然是闭源，不过至少可以看到自研IDE的市场需求。

**Comment by nobodxbodon** [comment]
刚更新了issue：https://youtrack.jetbrains.com/issue/PY-48747#focus=Comments-27-4974355.0-0
构建pycharm挺费劲，现在不大确定该如何改这个正则：`^[a-zA-Z0-9._]+[a-zA-Z0-9_]$`

**Comment by duolabmeng6** [comment]
> 刚更新了issue：https://youtrack.jetbrains.com/issue/PY-48747#focus=Comments-27-4974355.0-0
> 构建pycharm挺费劲，现在不大确定该如何改这个正则：`^[a-zA-Z0-9._]+[a-zA-Z0-9_]$`

```
def 文本_取出文本中汉字(欲处理文本: str) -> str:
    '返回文本中的所有汉字'
    result = re.findall(r"[\u4e00-\u9fa5]", 欲处理文本)
    return "".join(result)
```


目测

```
^[a-zA-Z0-9._\u4e00-\u9fa5]+[a-zA-Z0-9_\u4e00-\u9fa5]$
```

就可以

**Comment by duolabmeng6** [comment]
> > 大佬这个bug他们修复了没
> 
> 没看出是否已开始着手。从这个 [SO 帖子看来](https://stackoverflow.com/questions/53120356/pucharm-unittest-error-provide-a-qualified-name-of-function-class-or-a-module)，只要把 [isWellFormed](https://github.com/JetBrains/intellij-community/blob/76054d809dc7649d0df64ad1ecc45514feb0bc34/python/src/com/jetbrains/python/testing/PyTestsShared.kt#L285) 的条件放宽就可以，我在一开始建的 PY-49059 里也提到了，不知道他们是不是有其他的考虑。
> 
> 自己构建一个pycharm不知是否可行，有空的话可以试试。
> 
> 说个题外话，有没有认识自己搞开源IDE项目的？虽然现在有中文补全辅助插件，但毕竟受限于现有IDE的API和补全机制，长远来看必然有需求开发适合中文开发者的IDE（短期内也许需要倚靠定制现有IDE实现）。早先有过一些 [相关讨论](https://github.com/program-in-chinese/overview/issues/11)。最近看到 [hbuilderx](https://www.dcloud.io/hbuilderx.html)，虽然是闭源，不过至少可以看到自研IDE的市场需求。

测试一下

如果要编译python的话 中文文件名编译后就出现了无法引入的情况...

window下中文命名能够正常引入

整体上来看支持中文from 导包 如果没有编译的需求的话没问题的 为了兼容性或许英文文件名更合适...

**Comment by nobodxbodon** [comment]
嗯就用这个正则吧，没看到他们对issue回应，一会建个PR再说。

> mac 编译后中文文件名无法导包

不知“编译”是指？可否举个例子？

**Comment by duolabmeng6** [comment]
> 嗯就用这个正则吧，没看到他们对issue回应，一会建个PR再说。
> 
> > mac 编译后中文文件名无法导包
> 
> 不知“编译”是指？可否举个例子？

https://zhuanlan.zhihu.com/p/133303836

用 Nuitka把python转换为c mac下 中文导包失败...

**Comment by nobodxbodon** [comment]
刚给 pycharm 提交了个 pr。`\u4e00-\u9fa5` 仅是中文部分，所以用了 PyNames.isIdentifier 。

**Comment by nobodxbodon** [comment]
Nuitka 不支持非英文包路径？有没有相关 issue 呢？

**Comment by nobodxbodon** [comment]
Pycharm 的 pr 已合并在 [此 commit](https://github.com/JetBrains/intellij-community/commit/63aff5b7d98983613200c8434d16c05db6b85f9a)。 看看啥时候会包含在发布版里。
![Screen Shot 2021-07-02 at 12 04 09 AM](https://user-images.githubusercontent.com/392497/124234608-1b864c80-dac9-11eb-82bd-6986348e2671.png)
