### ISSUE TITLE
wx可视化界面设计器在哪里安装

### ISSUE THREAD

**Issue by 1431241631** [duolabmeng6/pyefun#2]
Wx可视化界面设计器在哪里安装

**Comment by duolabmeng6** [comment]
暂时没有哦 期待更加完善以后推出

**Comment by duolabmeng6** [comment]
目前易函数视窗可视化设计器的 pycharm 配合插件已开发 可视化工具还在设计之中

**Comment by duolabmeng6** [comment]
易函数视窗编程系统安装及使用教程 https://pyefun.readthedocs.io/zh_CN/latest/wxefun.html

已经发布了哈~可以下载体验

**Comment by 1431241631** [comment]
> 易函数视窗编程系统安装及使用教程 https://pyefun.readthedocs.io/zh_CN/latest/wxefun.html
> 
> 已经发布了哈~可以下载体验

帅的很，已经试了
