### ISSUE TITLE
你好 有关JS操作问题请教

### ISSUE THREAD

**Issue by Vang-z** [duolabmeng6/pyefun#39]
如下图, 精易模块中使用 `Js.计算表达式()`, `Js.清除()`
![1](https://user-images.githubusercontent.com/44422499/122323302-76f8fc00-cf59-11eb-9334-250e2cabf2ad.png)
如何在python中使用类似的操作呢? 我查看了源码好像没有提供这个方法的接口, 希望大佬赐教
![2](https://user-images.githubusercontent.com/44422499/122323454-af98d580-cf59-11eb-837b-b0085799a6ba.png)

**Comment by duolabmeng6** [comment]
```
from pyefun.javscript import *


js = javscript("JScript")
data = js.运行("1 + 2")
print(data, js.取运行环境())

js = javscript("Node")
data = js.运行("1 + 2")
print(data, js.取运行环境())

js = javscript("Node")
data = js.加载代码(""" 
function add(x, y) { 
  return x + y; 
} 
""")
data = js.执行("add", 1, 2)
print(data)
data = js.运行("add(1,2)")
print(data)

data = 运行js(""" 
function add(x, y) { 
  return x + y; 
} 
""", "add(1,2)")
print(data)


```

**Comment by Vang-z** [comment]
这个就是源生的execjs的用法, 但是目前问题是execjs没有类似计算表达式的方法, 所以想请教有没有类似的方法

**Comment by duolabmeng6** [comment]
```
js.运行("return ms.mousemove")
```
写个 return 就好了吧
