### ISSUE TITLE
网络session操作bug,session无效，cookies优化

### ISSUE THREAD

**Issue by 2535688890** [duolabmeng6/pyefun#46]
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L208
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L210
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L212
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L214
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L216
https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L218
**这里的`requests`应该使用`self._requests`**

https://github.com/duolabmeng6/pyefun/blob/8144fcf302e1a2ea17e377169dd6b08a1702e587/pyefun/networkUtil.py#L189
这里的_cookie应该判断是否为空字典，空字典就舍弃传入参数
```
if len(_cookie) > 0:
    传入参数['cookies'] = _cookie
````

**Comment by duolabmeng6** [comment]
from pyefun.eRequestsUtil import * # 易函数易用的请求模块

已经删除相关代码 重写了~
