### ISSUE TITLE
窗口设计器BUG

### ISSUE THREAD

**Issue by wuji530** [duolabmeng6/pyefun#48]
1.打开易函数窗口设计器，随意添加几个按钮和标签组件，然后修改窗口组件名称 “窗口1”  改为 LoginWindow，关闭窗口设计器
2.重新打开易函数窗口设计器，然后pycham会提示打开窗口设计器错误。之后窗口设计器打开之后只有空白窗口，组件名称又是 "窗口1",而且之前添加的组件都看不到
3.但是运行main.py脚本还是可以看到之前的组件。

**Comment by duolabmeng6** [comment]
窗口配置文件是跟脚本文件名关联的~
